name: Deploy to Render

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Trigger Render Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check for required secrets
        run: |
          if [ -z "${{ secrets.RENDER_API_KEY }}" ] || [ -z "${{ secrets.RENDER_SERVICE_ID }}" ]; then
            echo "ERROR: RENDER_API_KEY and/or RENDER_SERVICE_ID secrets are not set."
            echo "Please set repository secrets: RENDER_API_KEY (your Render API key) and RENDER_SERVICE_ID (the service id from Render)."
            exit 1
          fi

      - name: Trigger Render deploy via API
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
        run: |
          echo "Triggering deploy for Render service $RENDER_SERVICE_ID"
          resp=$(curl -s -X POST "https://api.render.com/v1/services/$RENDER_SERVICE_ID/deploys" \
            -H "Authorization: Bearer $RENDER_API_KEY" \
            -H "Content-Type: application/json" \
            -d '{"clearCache":false}')
          echo "Render response: $resp"
          # basic error check
          if echo "$resp" | grep -q '"errors"'; then
            echo "Render API returned an error:"; echo "$resp"; exit 1
          fi
